plugins {
    id 'fabric-loom' version "${fabric_loom_version}"
}

version = '1.0.0'
group = 'dev.mavenhaste.compat'

dependencies {
    minecraft "com.mojang:minecraft:${fabric_minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
