modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="maven_haste_neoforge_compat"
version="1.0.0"
displayName="Maven Haste NeoForge Compatibility"
description='''Minimal NeoForge project for Maven proxy compatibility checks.'''

[[dependencies.maven_haste_neoforge_compat]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.maven_haste_neoforge_compat]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
