//! Generates `MIGRATIONS` from the `migrations/` directory at build time, so
//! the directory is the single source of truth: adding a migration only means
//! dropping a new `NUM-NAME.sql` file into `migrations/` and rebuilding.
//!
//! Ordering is decided by the parsed leading number, not by the file name, so
//! zero-padding is optional (`1-init.sql` and `10-ten.sql` sort numerically).
//! Files that do not follow the pattern are ignored; duplicate numbers abort
//! the build.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo");
    let migrations_dir = Path::new(&manifest_dir).join("migrations");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by Cargo");

    let mut ordered: Vec<(usize, String)> = Vec::new();
    for entry in fs::read_dir(&migrations_dir).expect("failed to read the migrations directory") {
        let entry = entry.expect("failed to read a migrations directory entry");
        let file_name = entry.file_name();
        let name = file_name
            .to_str()
            .expect("migration file names must be valid UTF-8");
        if let Some(number) = migration_number(name) {
            ordered.push((number, name.to_owned()));
        }
    }
    ordered.sort_by_key(|(number, _)| *number);
    if let Some(pair) = ordered.windows(2).find(|window| window[0].0 == window[1].0) {
        panic!(
            "duplicate migration number {} in {} and {}",
            pair[0].0, pair[0].1, pair[1].1
        );
    }

    let entries = ordered
        .iter()
        .map(|(_, name)| {
            format!(
                "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/migrations/\", {name:?})),"
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let generated = format!(
        "// Generated by build.rs from the `migrations/` directory; do not edit.\n\
         pub(crate) const MIGRATIONS: &[&str] = &[\n{entries}\n];\n"
    );
    fs::write(Path::new(&out_dir).join("migrations.rs"), generated)
        .expect("failed to write the generated migrations module");

    println!("cargo:rerun-if-changed=migrations");
}

/// Returns the leading migration number of a `NUM-NAME.sql` file name.
fn migration_number(name: &str) -> Option<usize> {
    if !name.ends_with(".sql") {
        return None;
    }
    let (prefix, _) = name.split_once('-')?;
    prefix.parse::<usize>().ok()
}
