modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="maven_haste_forge_compat"
version="1.0.0"
displayName="Maven Haste Forge Compatibility"
description='''Minimal Forge project for Maven proxy compatibility checks.'''

[[dependencies.maven_haste_forge_compat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.maven_haste_forge_compat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
